### ISSUE TITLE
User acess permision view only

### ISSUE THREAD

**Issue by dheer99** [snipe/snipe-it#2363]
#### Expected Behavior (or desired behavior if a feature request)

View rights User will not be able to edit any asset/license/accessories !

(what you expect to happen goes here)

-----

#### Actual Behavior

any user created with view only permission, has also able to edit the asset.

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running  : v3 (stable release)
- What OS and web server you're running Snipe-IT on (windows server 2008, IIS &+)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) :  (manual installation)
- If you're getting an error in your browser, include that error  :- no error 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error :- N/A
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
I believe this is fixed on master and develop

**Comment by dheer99** [comment]
not able to understand, apology for this, actually i am not software expert, 
just needed this project, suites my requirement. setup as per guideline on web portal.
i will be thankful, if you explain me, how to create a user with only having the rights to view all assets, but not to able to edit it.

**Comment by snipe** [comment]
Please upgrade to the latest version.

**Comment by dheer99** [comment]
Hi Team Snipe, i am using Latest version. please reopen this issue, i am still not get my answer !!

**Comment by dheer99** [comment]
Version v3.1-84-g139325d just upgraded, but still the same issue, view access user also able to edit assets.

**Comment by dmeltzer** [comment]
At this point the "view" permission also allows editing, creation, and deletion.  Finer granularity of permissions is planned, but does not currently exist.

**Comment by dheer99** [comment]
Thanks, so this request can be treated as feature request for Snipe-IT :) 
Please update me once it's available for use.
also if it is possible non admin user dashboard will be same as admin user it's really helps.

**Comment by snipe** [comment]
This feature request already exists. 

> also if it is possible non admin user dashboard will be same as admin user it's really helps. 

I don't know what this means.

**Comment by dheer99** [comment]
Sorry to say again, but i am unable to find such feature, if user grant with view access, it's also able to edit the asset, which we dont want.

the meaning of same dashboard, in simple the first page after web login on toll, will be same as we able to see via admin user. a summary of asset/license/etc.

**Comment by snipe** [comment]
Why would a non-admin need to see the admin dashboard?

**Comment by dheer99** [comment]
hi Snipe Team, it's only to look grate, but it's fine if it will make you quite busy, you can close this request.

although , i am still unable to find the solution for creating a view only user which can not edit any asset.

**Comment by dmeltzer** [comment]
@dheer99 : The commit to allow view-only users just hit the most recent develop branch in the last few hours.  You can try it on the demo (http://demo.snipeitapp.com) or, if it's a priority, you could update to the latest git sources.  Be aware though that these are less tested than the released version and so potentially have more issues (Though usually more fixes as well).

**Comment by dheer99** [comment]
Thanks Team, i am happy to wait for stable version ! thanks for taking this request on your consideration

**Comment by michaelfahy** [comment]
> Why would a non-admin need to see the admin dashboard?

We have, for example, student workers who need to be able to view all assets but not to edit them.
