### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jayzer08** [snipe/snipe-it#290]
Hi!

Can you help me how to install snipe-it in Xampp windows 8.1??

thanks

**Comment by salam82** [comment]
![1](https://cloud.githubusercontent.com/assets/7134646/9795099/355ad95e-5808-11e5-804e-cf7c1e76bcb8.PNG)
![2](https://cloud.githubusercontent.com/assets/7134646/9795100/356243ba-5808-11e5-82d8-50a47c03f0ab.PNG)

What is that I am missing out????

**Comment by snipe** [comment]
http://docs.snipeitapp.com/common-issues.html#while-running-composer-interventionimage-dev-master-requires-ext-fileinfo---gt-the-requested-php-extension-fileinfo-is-missing-or-not-enabled-on-your-system

**Comment by salam82** [comment]
Thank you the above problem is solved but.... please this too
![3](https://cloud.githubusercontent.com/assets/7134646/9796227/7ad1abb0-580e-11e5-8f92-937b0e76f23b.PNG)

**Comment by snipe** [comment]
You need to ste your document root to `public`. `public` should not be in the url.

**Comment by salam82** [comment]
Okay! a little guidance please. not too much expert :p

**Comment by snipe** [comment]
@salam82 All of this is already documented. Please select your OS and follow the directions from there: http://docs.snipeitapp.com/installation/server/index.html

**Comment by psychfox** [comment]
Hi snipe,

Can i ask some help on the installation. i followed the instructions above but still getting internal Server error. i got the php artisan app:install completed without errors.

whats next? thanks

**Comment by snipe** [comment]
@psychfox http://docs.snipeitapp.com/getting-help.html

**Comment by snipe** [comment]
@psychfox also please start a new ticket next time, since we don't yet know if your issue is related to this original ticket. Thanks!

**Comment by psychfox** [comment]
Hi Snipe,

i have tried the steps mentioned by madd15 but i get this error below.
all the steps where followed correctly and got successful results.

![screen shot 2015-09-30 at 9 20 12 am](https://cloud.githubusercontent.com/assets/14256581/10182250/a0b123f6-6754-11e5-80a4-0d99d7728fe8.png)

**Comment by psychfox** [comment]
btw, i place the copied database.php xampp\htdocs\snipeit\app\config\local on this path xampp\htdocs\snipeit\app\config\ after modifying it.

**Comment by snipe** [comment]
@psychfox need you to turn debugging on so we can see actual errors

**Comment by psychfox** [comment]
hi Snipe,

Thanks, i think im using the production folder instead of the local. its working now. but how come it does not read the SetEnv LARAVEL_ENV local that i set to vhosts.conf of apache?

**Comment by snipe** [comment]
Its not looking for an environmental variable there. To set it to local, change 'bootstrap/start.php' in the environmental array to your host name (not domain name).

**Comment by psychfox** [comment]
Hi Snipe, 

here is my bootstrap/start.php.. kindly enlighten me on this. i just want to use this as local. thanks a lot

![capture](https://cloud.githubusercontent.com/assets/14256581/10183006/8d1fb2c2-675d-11e5-9b87-df465364f126.PNG)

**Comment by snipe** [comment]
You have the same value for local and production. Change the one for production to something else.

Also, you probably want to run this in production mode unless you're planning on developing code for it.

**Comment by psychfox** [comment]
alright. thanks snipe appreciate the clarification for this one. :+1:  :+1: 
 :100: 
ticket can be close.

Thanks also for Madd15 for the instructions above which is followed. :+1:

**Comment by moniruss** [comment]
Hi, every time I try installing composer, its giving downloading error in midway! Tried it in several machines. I am giving a snapshot here:
![error1](https://cloud.githubusercontent.com/assets/16552454/12108946/1452cc44-b3a7-11e5-81d8-7e8f4c5f7a94.png)
Another issue is i am i have set up a computer with an ip and there i am using xampp to run server with port 10 (say: 192.168.255.29:10 thats what i put in my laptop to access it remotely  through similar network). now what will be recommended environment? local or production? and what will be the changes in bootstrap/start.php, app/config/(local or production folder?)/(app.php, database.php)
There's also this thing with the key. How to generate it? from command prompt? but there it says something like no artisan found and etc. So let me know please asap and guide me to somewhere if there's already this issue specifically fixed.

**Comment by mileper2nd** [comment]
@moniruss You  must login to your github account and generate a token key, which you will enter (noticing yourscreenshot) when it will ask you for **Token(hidden):**

**Comment by balaji0408** [comment]
i'm not able to find start.php in bootstrap folder 

bootstrap/start.php 

plz guide me in installing the snipe-it using xampp

**Comment by moniruss** [comment]
@balaji0408 hi, when you extract the snipeit downloaded zip folder, inside the folder, there will be bootstrap folder. there inside will be start.php file. you have to extract the zip file into your localhost root directory. For further assistance, you may directly ask me in gmail if you want. I also had a few difficulties at first, but it gets easier once you get used to it.

**Comment by snipe** [comment]
Those instructions were for v2. It is handled via env file in v3. Please see the docs at https://snipe-it.readme.io

**Comment by jmemmott** [comment]
I am having issue installing v3, noticed this was posted on back in the past - but link is dead http://docs.snipeitapp.com/common-issues.html#while-running-composer-interventionimage-dev-master-requires-ext-fileinfo---gt-the-requested-php-extension-fileinfo-is-missing-or-not-enabled-on-your-system


![capture](https://cloud.githubusercontent.com/assets/21296394/18036417/dd600e2e-6d26-11e6-911a-bdc9e03af057.PNG)
