### ISSUE TITLE
Failed Pre-Flight Check

### ISSUE THREAD

**Issue by FOOSAYS** [snipe/snipe-it#3787]
#### Expected Behavior (or desired behavior if a feature request)

Create database tables

-----

#### Actual Behavior

Whoops, looks like something went wrong.

Error 1/2: PDOException in Connection.php line 457:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '''' at line 1

Error 2/2: QueryException in Connection.php line 729:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '''' at line 1 (SQL: ALTER TABLE licenses CHANGE notes notes TEXT DEFAULT ''NULL'')
-----

#### Please confirm you have done the following before posting your bug report:

- [Y] I have enabled debug mode
- [Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
--- 3.6.6

- What OS and web server you're running Snipe-IT on
--- Windows Server 2012 R2
--- IIS 7

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
--- manual installation

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
--- see above

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
--- https://assets.readcasedhole.com/setup/migrate?
--- "Create Database Tables" button in pre-flight checks

- If a stacktrace is provided in the error, include that too.
--- 1/2
in Connection.php line 457
at PDO->prepare('ALTER TABLE licenses CHANGE notes notes TEXT DEFAULT ''NULL''') in Connection.php line 457
at Connection->Illuminate\Database\{closure}(object(MySqlConnection), 'ALTER TABLE licenses CHANGE notes notes TEXT DEFAULT ''NULL''', array()) in Connection.php line 722
at Connection->runQueryCallback('ALTER TABLE licenses CHANGE notes notes TEXT DEFAULT ''NULL''', array(), object(Closure)) in Connection.php line 685
at Connection->run('ALTER TABLE licenses CHANGE notes notes TEXT DEFAULT ''NULL''', array(), object(Closure)) in Connection.php line 458
at Connection->statement('ALTER TABLE licenses CHANGE notes notes TEXT DEFAULT ''NULL''') in Blueprint.php line 83
at Blueprint->build(object(MySqlConnection), object(MySqlGrammar)) in Builder.php line 229
at Builder->build(object(Blueprint)) in Builder.php line 130
at Builder->table('licenses', object(Closure)) in compiled.php line 6327
at Facade::__callStatic('table', array('licenses', object(Closure))) in 2015_02_12_024100_change_license_notes_type.php line 15
at ChangeLicenseNotesType->up() in Migrator.php line 147
at Migrator->runUp('2015_02_12_024100_change_license_notes_type', '2', false) in Migrator.php line 117
at Migrator->runMigrationList(array('2015_02_12_024100_change_license_notes_type', '2015_02_17_231020_add_localonly_to_settings', '2015_02_19_222322_add_logo_and_colors_to_settings', '2015_02_24_072043_add_alerts_to_settings', '2015_02_25_022931_add_eula_fields', '2015_02_25_204513_add_accessories_table', '2015_02_26_091228_add_accessories_user_table', '2015_02_26_115128_add_deleted_at_models', '2015_02_26_233005_add_category_type', '2015_03_01_231912_update_accepted_at_to_acceptance_id', '2015_03_05_011929_add_qr_type_to_settings', '2015_03_18_055327_add_note_to_user', '2015_04_29_234704_add_slack_to_settings', '2015_05_04_085151_add_parent_id_to_locations_table', '2015_05_22_124421_add_reassignable_to_licenses', '2015_06_10_003314_fix_default_for_user_notes', '2015_06_10_003554_create_consumables', '2015_06_15_183253_move_email_to_username', '2015_06_23_070346_make_email_nullable', '2015_06_26_213716_create_asset_maintenances_table', '2015_07_04_212443_create_custom_fields_table', '2015_07_09_014359_add_currency_to_settings_and_locations', '2015_07_21_122022_add_expected_checkin_date_to_asset_logs', '2015_07_24_093845_add_checkin_email_to_category_table', '2015_07_25_055415_remove_email_unique_constraint', '2015_07_29_230054_add_thread_id_to_asset_logs_table', '2015_07_31_015430_add_accepted_to_assets', '2015_09_09_195301_add_custom_css_to_settings', '2015_09_21_235926_create_custom_field_custom_fieldset', '2015_09_22_000104_create_custom_fieldsets', '2015_09_22_003321_add_fieldset_id_to_assets', '2015_09_22_003413_migrate_mac_address', '2015_09_28_003314_fix_default_purchase_order', '2015_10_01_024551_add_accessory_consumable_price_info', '2015_10_12_192706_add_brand_to_settings', '2015_10_22_003314_fix_defaults_accessories', '2015_10_23_182625_add_checkout_time_and_expected_checkout_date_to_assets', '2015_11_05_061015_create_companies_table', '2015_11_05_061115_add_company_id_to_consumables_table', '2015_11_05_183749_image', '2015_11_06_092038_add_company_id_to_accessories_table', '2015_11_06_100045_add_company_id_to_users_table', '2015_11_06_134742_add_company_id_to_licenses_table', '2015_11_08_035832_add_company_id_to_assets_table', '2015_11_08_222305_add_ldap_fields_to_settings', '2015_11_15_151803_add_full_multiple_companies_support_to_settings_table', '2015_11_26_195528_import_ldap_settings', '2015_11_30_191504_remove_fk_company_id', '2015_12_21_193006_add_ldap_server_cert_ignore_to_settings_table', '2015_12_30_233509_add_timestamp_and_userId_to_custom_fields', '2015_12_30_233658_add_timestamp_and_userId_to_custom_fieldsets', '2016_01_28_041048_add_notes_to_models', '2016_02_19_070119_add_remember_token_to_users_table', '2016_02_19_073625_create_password_resets_table', '2016_03_02_193043_add_ldap_flag_to_users', '2016_03_02_220517_update_ldap_filter_to_longer_field', '2016_03_08_225351_create_components_table', '2016_03_09_024038_add_min_stock_to_tables', '2016_03_10_133849_add_locale_to_users', '2016_03_10_135519_add_locale_to_settings', '2016_03_11_185621_add_label_settings_to_settings', '2016_03_22_125911_fix_custom_fields_regexes', '2016_04_28_141554_add_show_to_users', '2016_05_16_164733_add_model_mfg_to_consumable', '2016_05_19_180351_add_alt_barcode_settings', '2016_05_19_191146_add_alter_interval', '2016_05_19_192226_add_inventory_threshold', '2016_05_20_024859_remove_option_keys_from_settings_table', '2016_05_20_143758_remove_option_value_from_settings_table', '2016_06_01_140218_add_email_domain_and_format_to_settings', '2016_06_22_160725_add_user_id_to_maintenances', '2016_07_13_150015_add_is_ad_to_settings', '2016_07_14_153609_add_ad_domain_to_settings', '2016_07_22_003348_fix_custom_fields_regex_stuff', '2016_07_22_054850_one_more_mac_addr_fix', '2016_07_22_143045_add_port_to_ldap_settings', '2016_07_22_153432_add_tls_to_ldap_settings', '2016_07_27_211034_add_zerofill_to_settings', '2016_08_02_124944_add_color_to_statuslabel', '2016_08_04_134500_add_disallow_ldap_pw_sync_to_settings', '2016_08_09_002225_add_manufacturer_to_licenses', '2016_08_12_121613_add_manufacturer_to_accessories_table', '2016_08_23_143353_add_new_fields_to_custom_fields', '2016_08_23_145619_add_show_in_nav_to_status_labels', '2016_08_30_084634_make_purchase_cost_nullable', '2016_09_01_141051_add_requestable_to_asset_model', '2016_09_02_001448_create_checkout_requests_table', '2016_09_04_180400_create_actionlog_table', '2016_09_04_182149_migrate_asset_log_to_action_log', '2016_09_19_235935_fix_fieldtype_for_target_type', '2016_09_23_140722_fix_modelno_in_consumables_to_string', '2016_09_28_231359_add_company_to_logs', '2016_10_14_130709_fix_order_number_to_varchar', '2016_10_16_015024_rename_modelno_to_model_number', '2016_10_16_015211_rename_consumable_modelno_to_model_number', '2016_10_16_143235_rename_model_note_to_notes', '2016_10_16_165052_rename_component_total_qty_to_qty', '2016_10_19_145520_fix_order_number_in_components_to_string', '2016_10_27_151715_add_serial_to_components', '2016_10_27_213251_increase_serial_field_capacity', '2016_10_29_002724_enable_2fa_fields', '2016_10_29_082408_add_signature_to_acceptance', '2016_11_01_030818_fix_forgotten_filename_in_action_logs', '2016_11_13_020954_rename_component_serial_number_to_serial', '2016_11_16_172119_increase_purchase_cost_size', '2016_11_17_161317_longer_state_field_in_location', '2016_11_17_193706_add_model_number_to_accessories', '2016_11_24_160405_add_missing_target_type_to_logs_table', '2016_12_07_173720_increase_size_of_state_in_suppliers'), array('pretend' => false, 'step' => false)) in Migrator.php line 86
at Migrator->run('C:\inetpub\wwwroot\snipe-it-3.6.6\database\migrations', array('pretend' => false, 'step' => false)) in MigrateCommand.php line 76
at MigrateCommand->fire()
at call_user_func_array(array(object(MigrateCommand), 'fire'), array()) in compiled.php line 1257
at Container->call(array(object(MigrateCommand), 'fire')) in Command.php line 169
at Command->execute(object(ArrayInput), object(BufferedOutput)) in Command.php line 256
at Command->run(object(ArrayInput), object(BufferedOutput)) in Command.php line 155
at Command->run(object(ArrayInput), object(BufferedOutput)) in Application.php line 794
at Application->doRunCommand(object(MigrateCommand), object(ArrayInput), object(BufferedOutput)) in Application.php line 186
at Application->doRun(object(ArrayInput), object(BufferedOutput)) in Application.php line 117
at Application->run(object(ArrayInput), object(BufferedOutput)) in Application.php line 64
at Application->call('migrate', object(Collection)) in Kernel.php line 170
at Kernel->call('migrate', array('--force' => true)) in compiled.php line 6327
at Facade::__callStatic('call', array('migrate', array('--force' => true))) in SettingsController.php line 247
at SettingsController->getSetupMigrate()
at call_user_func_array(array(object(SettingsController), 'getSetupMigrate'), array()) in compiled.php line 9424
at Controller->callAction('getSetupMigrate', array()) in compiled.php line 9486
at ControllerDispatcher->call(object(SettingsController), object(Route), 'getSetupMigrate') in compiled.php line 9466
at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in compiled.php line 9948
at Pipeline->then(object(Closure)) in compiled.php line 9467
at ControllerDispatcher->callWithinStack(object(SettingsController), object(Route), object(Request), 'getSetupMigrate') in compiled.php line 9454
at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\SettingsController', 'getSetupMigrate') in compiled.php line 8524
at Route->runController(object(Request)) in compiled.php line 8511
at Route->run(object(Request)) in compiled.php line 8225
at Router->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForTwoFactor.php line 49
at CheckForTwoFactor->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForTwoFactor), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckLocale.php line 42
at CheckLocale->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckLocale), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 3225
at VerifyCsrfToken->handle(object(Request), object(Closure))
at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13213
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13150
at EncryptCookies->handle(object(Request), object(Closure))
at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in compiled.php line 9948
at Pipeline->then(object(Closure)) in compiled.php line 8226
at Router->runRouteWithinStack(object(Route), object(Request)) in compiled.php line 8217
at Router->dispatchToRoute(object(Request)) in compiled.php line 8207
at Router->dispatch(object(Request)) in compiled.php line 2419
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Debugbar.php line 49
at Debugbar->handle(object(Request), object(Closure))
at call_user_func_array(array(object(Debugbar), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForDebug), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TrustProxies.php line 46
at TrustProxies->handle(object(Request), object(Closure))
at call_user_func_array(array(object(TrustProxies), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForSetup.php line 35
at CheckForSetup->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForSetup), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))
at call_user_func_array(array(object(NosniffGuard), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in XssProtectHeader.php line 17
at XssProtectHeader->handle(object(Request), object(Closure))
at call_user_func_array(array(object(XssProtectHeader), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))
at call_user_func_array(array(object(FrameGuard), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13474
at ShareErrorsFromSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 11964
at StartSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 145
at CheckForMaintenanceMode->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in compiled.php line 9948
at Pipeline->then(object(Closure)) in compiled.php line 2366
at Kernel->sendRequestThroughRouter(object(Request)) in compiled.php line 2350
at Kernel->handle(object(Request)) in index.php line 59

--- 2/2
in Connection.php line 729
at Connection->runQueryCallback('ALTER TABLE licenses CHANGE notes notes TEXT DEFAULT ''NULL''', array(), object(Closure)) in Connection.php line 685
at Connection->run('ALTER TABLE licenses CHANGE notes notes TEXT DEFAULT ''NULL''', array(), object(Closure)) in Connection.php line 458
at Connection->statement('ALTER TABLE licenses CHANGE notes notes TEXT DEFAULT ''NULL''') in Blueprint.php line 83
at Blueprint->build(object(MySqlConnection), object(MySqlGrammar)) in Builder.php line 229
at Builder->build(object(Blueprint)) in Builder.php line 130
at Builder->table('licenses', object(Closure)) in compiled.php line 6327
at Facade::__callStatic('table', array('licenses', object(Closure))) in 2015_02_12_024100_change_license_notes_type.php line 15
at ChangeLicenseNotesType->up() in Migrator.php line 147
at Migrator->runUp('2015_02_12_024100_change_license_notes_type', '2', false) in Migrator.php line 117
at Migrator->runMigrationList(array('2015_02_12_024100_change_license_notes_type', '2015_02_17_231020_add_localonly_to_settings', '2015_02_19_222322_add_logo_and_colors_to_settings', '2015_02_24_072043_add_alerts_to_settings', '2015_02_25_022931_add_eula_fields', '2015_02_25_204513_add_accessories_table', '2015_02_26_091228_add_accessories_user_table', '2015_02_26_115128_add_deleted_at_models', '2015_02_26_233005_add_category_type', '2015_03_01_231912_update_accepted_at_to_acceptance_id', '2015_03_05_011929_add_qr_type_to_settings', '2015_03_18_055327_add_note_to_user', '2015_04_29_234704_add_slack_to_settings', '2015_05_04_085151_add_parent_id_to_locations_table', '2015_05_22_124421_add_reassignable_to_licenses', '2015_06_10_003314_fix_default_for_user_notes', '2015_06_10_003554_create_consumables', '2015_06_15_183253_move_email_to_username', '2015_06_23_070346_make_email_nullable', '2015_06_26_213716_create_asset_maintenances_table', '2015_07_04_212443_create_custom_fields_table', '2015_07_09_014359_add_currency_to_settings_and_locations', '2015_07_21_122022_add_expected_checkin_date_to_asset_logs', '2015_07_24_093845_add_checkin_email_to_category_table', '2015_07_25_055415_remove_email_unique_constraint', '2015_07_29_230054_add_thread_id_to_asset_logs_table', '2015_07_31_015430_add_accepted_to_assets', '2015_09_09_195301_add_custom_css_to_settings', '2015_09_21_235926_create_custom_field_custom_fieldset', '2015_09_22_000104_create_custom_fieldsets', '2015_09_22_003321_add_fieldset_id_to_assets', '2015_09_22_003413_migrate_mac_address', '2015_09_28_003314_fix_default_purchase_order', '2015_10_01_024551_add_accessory_consumable_price_info', '2015_10_12_192706_add_brand_to_settings', '2015_10_22_003314_fix_defaults_accessories', '2015_10_23_182625_add_checkout_time_and_expected_checkout_date_to_assets', '2015_11_05_061015_create_companies_table', '2015_11_05_061115_add_company_id_to_consumables_table', '2015_11_05_183749_image', '2015_11_06_092038_add_company_id_to_accessories_table', '2015_11_06_100045_add_company_id_to_users_table', '2015_11_06_134742_add_company_id_to_licenses_table', '2015_11_08_035832_add_company_id_to_assets_table', '2015_11_08_222305_add_ldap_fields_to_settings', '2015_11_15_151803_add_full_multiple_companies_support_to_settings_table', '2015_11_26_195528_import_ldap_settings', '2015_11_30_191504_remove_fk_company_id', '2015_12_21_193006_add_ldap_server_cert_ignore_to_settings_table', '2015_12_30_233509_add_timestamp_and_userId_to_custom_fields', '2015_12_30_233658_add_timestamp_and_userId_to_custom_fieldsets', '2016_01_28_041048_add_notes_to_models', '2016_02_19_070119_add_remember_token_to_users_table', '2016_02_19_073625_create_password_resets_table', '2016_03_02_193043_add_ldap_flag_to_users', '2016_03_02_220517_update_ldap_filter_to_longer_field', '2016_03_08_225351_create_components_table', '2016_03_09_024038_add_min_stock_to_tables', '2016_03_10_133849_add_locale_to_users', '2016_03_10_135519_add_locale_to_settings', '2016_03_11_185621_add_label_settings_to_settings', '2016_03_22_125911_fix_custom_fields_regexes', '2016_04_28_141554_add_show_to_users', '2016_05_16_164733_add_model_mfg_to_consumable', '2016_05_19_180351_add_alt_barcode_settings', '2016_05_19_191146_add_alter_interval', '2016_05_19_192226_add_inventory_threshold', '2016_05_20_024859_remove_option_keys_from_settings_table', '2016_05_20_143758_remove_option_value_from_settings_table', '2016_06_01_140218_add_email_domain_and_format_to_settings', '2016_06_22_160725_add_user_id_to_maintenances', '2016_07_13_150015_add_is_ad_to_settings', '2016_07_14_153609_add_ad_domain_to_settings', '2016_07_22_003348_fix_custom_fields_regex_stuff', '2016_07_22_054850_one_more_mac_addr_fix', '2016_07_22_143045_add_port_to_ldap_settings', '2016_07_22_153432_add_tls_to_ldap_settings', '2016_07_27_211034_add_zerofill_to_settings', '2016_08_02_124944_add_color_to_statuslabel', '2016_08_04_134500_add_disallow_ldap_pw_sync_to_settings', '2016_08_09_002225_add_manufacturer_to_licenses', '2016_08_12_121613_add_manufacturer_to_accessories_table', '2016_08_23_143353_add_new_fields_to_custom_fields', '2016_08_23_145619_add_show_in_nav_to_status_labels', '2016_08_30_084634_make_purchase_cost_nullable', '2016_09_01_141051_add_requestable_to_asset_model', '2016_09_02_001448_create_checkout_requests_table', '2016_09_04_180400_create_actionlog_table', '2016_09_04_182149_migrate_asset_log_to_action_log', '2016_09_19_235935_fix_fieldtype_for_target_type', '2016_09_23_140722_fix_modelno_in_consumables_to_string', '2016_09_28_231359_add_company_to_logs', '2016_10_14_130709_fix_order_number_to_varchar', '2016_10_16_015024_rename_modelno_to_model_number', '2016_10_16_015211_rename_consumable_modelno_to_model_number', '2016_10_16_143235_rename_model_note_to_notes', '2016_10_16_165052_rename_component_total_qty_to_qty', '2016_10_19_145520_fix_order_number_in_components_to_string', '2016_10_27_151715_add_serial_to_components', '2016_10_27_213251_increase_serial_field_capacity', '2016_10_29_002724_enable_2fa_fields', '2016_10_29_082408_add_signature_to_acceptance', '2016_11_01_030818_fix_forgotten_filename_in_action_logs', '2016_11_13_020954_rename_component_serial_number_to_serial', '2016_11_16_172119_increase_purchase_cost_size', '2016_11_17_161317_longer_state_field_in_location', '2016_11_17_193706_add_model_number_to_accessories', '2016_11_24_160405_add_missing_target_type_to_logs_table', '2016_12_07_173720_increase_size_of_state_in_suppliers'), array('pretend' => false, 'step' => false)) in Migrator.php line 86
at Migrator->run('C:\inetpub\wwwroot\snipe-it-3.6.6\database\migrations', array('pretend' => false, 'step' => false)) in MigrateCommand.php line 76
at MigrateCommand->fire()
at call_user_func_array(array(object(MigrateCommand), 'fire'), array()) in compiled.php line 1257
at Container->call(array(object(MigrateCommand), 'fire')) in Command.php line 169
at Command->execute(object(ArrayInput), object(BufferedOutput)) in Command.php line 256
at Command->run(object(ArrayInput), object(BufferedOutput)) in Command.php line 155
at Command->run(object(ArrayInput), object(BufferedOutput)) in Application.php line 794
at Application->doRunCommand(object(MigrateCommand), object(ArrayInput), object(BufferedOutput)) in Application.php line 186
at Application->doRun(object(ArrayInput), object(BufferedOutput)) in Application.php line 117
at Application->run(object(ArrayInput), object(BufferedOutput)) in Application.php line 64
at Application->call('migrate', object(Collection)) in Kernel.php line 170
at Kernel->call('migrate', array('--force' => true)) in compiled.php line 6327
at Facade::__callStatic('call', array('migrate', array('--force' => true))) in SettingsController.php line 247
at SettingsController->getSetupMigrate()
at call_user_func_array(array(object(SettingsController), 'getSetupMigrate'), array()) in compiled.php line 9424
at Controller->callAction('getSetupMigrate', array()) in compiled.php line 9486
at ControllerDispatcher->call(object(SettingsController), object(Route), 'getSetupMigrate') in compiled.php line 9466
at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in compiled.php line 9948
at Pipeline->then(object(Closure)) in compiled.php line 9467
at ControllerDispatcher->callWithinStack(object(SettingsController), object(Route), object(Request), 'getSetupMigrate') in compiled.php line 9454
at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\SettingsController', 'getSetupMigrate') in compiled.php line 8524
at Route->runController(object(Request)) in compiled.php line 8511
at Route->run(object(Request)) in compiled.php line 8225
at Router->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForTwoFactor.php line 49
at CheckForTwoFactor->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForTwoFactor), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckLocale.php line 42
at CheckLocale->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckLocale), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 3225
at VerifyCsrfToken->handle(object(Request), object(Closure))
at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13213
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13150
at EncryptCookies->handle(object(Request), object(Closure))
at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in compiled.php line 9948
at Pipeline->then(object(Closure)) in compiled.php line 8226
at Router->runRouteWithinStack(object(Route), object(Request)) in compiled.php line 8217
at Router->dispatchToRoute(object(Request)) in compiled.php line 8207
at Router->dispatch(object(Request)) in compiled.php line 2419
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Debugbar.php line 49
at Debugbar->handle(object(Request), object(Closure))
at call_user_func_array(array(object(Debugbar), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForDebug), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TrustProxies.php line 46
at TrustProxies->handle(object(Request), object(Closure))
at call_user_func_array(array(object(TrustProxies), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForSetup.php line 35
at CheckForSetup->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForSetup), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))
at call_user_func_array(array(object(NosniffGuard), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in XssProtectHeader.php line 17
at XssProtectHeader->handle(object(Request), object(Closure))
at call_user_func_array(array(object(XssProtectHeader), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))
at call_user_func_array(array(object(FrameGuard), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13474
at ShareErrorsFromSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 11964
at StartSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 145
at CheckForMaintenanceMode->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in compiled.php line 9948
at Pipeline->then(object(Closure)) in compiled.php line 2366
at Kernel->sendRequestThroughRouter(object(Request)) in compiled.php line 2350
at Kernel->handle(object(Request)) in index.php line 59

- Any errors that appear in your browser's error console.
--- Failed to load resource: the server responded with a status of 500 (Internal Server Error)

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
--- No, pre-flight checks
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
--- [laravel.txt](https://github.com/snipe/snipe-it/files/1176758/laravel.txt)

--- 2017-07-26 13:49:05 192.168.202.16 GET / - 443 - 192.168.202.16 Mozilla/5.0+(Windows+NT+6.3;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/59.0.3071.115+Safari/537.36 - 302 0 0 3796
2017-07-26 13:49:07 192.168.202.16 GET /.env - 443 - 192.168.202.16 - - 200 0 0 611
2017-07-26 13:49:07 192.168.202.16 GET /setup - 443 - 192.168.202.16 Mozilla/5.0+(Windows+NT+6.3;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/59.0.3071.115+Safari/537.36 - 200 0 0 1819
2017-07-26 13:49:07 192.168.202.16 GET /assets/fonts/fontawesome-webfont.woff2 v=4.5.0 443 - 192.168.202.16 Mozilla/5.0+(Windows+NT+6.3;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/59.0.3071.115+Safari/537.36 https://assets.readcasedhole.com/assets/css/font-awesome.min.css 404 3 50 7
2017-07-26 13:49:12 192.168.202.16 GET /setup/migrate - 443 - 192.168.202.16 Mozilla/5.0+(Windows+NT+6.3;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/59.0.3071.115+Safari/537.36 https://assets.readcasedhole.com/setup 500 0 0 2146

- Include what you've done so far in the installation, and if you got any error messages along the way.
--- confirmed databases are not in strict mode
--- confirmed MySQL database credentials are correct in .env
--- tested using DB root credentials
--- recreated database according to [https://snipe-it.readme.io/docs/creating-a-database-and-user](url)
- Indicate whether or not you've manually edited any data directly in the database
--- No

**Comment by TheWhexican87** [comment]
Having the same error at the same point in the Pre-Flight setup.  

Running PHP 7.1, MariaDB 10.2, running on Microsoft IIS

**Comment by FOOSAYS** [comment]
Sorry, I forgot to mention.
I am also running

PHP 7.1 and Maria 10.2

**Comment by snipe** [comment]
What happens if you try to run the migrations manually? (`php artisan migrate`)

**Comment by FOOSAYS** [comment]
I get the following entries in the laravel.log, which seem to be similar/same as displayed during the pre-flight check


[2017-07-31 07:34:06] production.ERROR: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '''' at line 1 in C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Connection.php:457
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Connection.php(457): PDO->prepare('ALTER TABLE lic...')
#1 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'ALTER TABLE lic...', Array)
#2 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Connection.php(685): Illuminate\Database\Connection->runQueryCallback('ALTER TABLE lic...', Array, Object(Closure))
#3 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Connection.php(458): Illuminate\Database\Connection->run('ALTER TABLE lic...', Array, Object(Closure))
#4 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Schema\Blueprint.php(83): Illuminate\Database\Connection->statement('ALTER TABLE lic...')
#5 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(229): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#6 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(130): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#7 C:\inetpub\wwwroot\snipe-it-3.6.6\bootstrap\cache\compiled.php(6327): Illuminate\Database\Schema\Builder->table('licenses', Object(Closure))
#8 C:\inetpub\wwwroot\snipe-it-3.6.6\database\migrations\2015_02_12_024100_change_license_notes_type.php(15): Illuminate\Support\Facades\Facade::__callStatic('table', Array)
#9 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(147): ChangeLicenseNotesType->up()
#10 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(117): Illuminate\Database\Migrations\Migrator->runUp('2015_02_12_0241...', 2, false)
#11 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(86): Illuminate\Database\Migrations\Migrator->runMigrationList(Array, Array)
#12 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(76): Illuminate\Database\Migrations\Migrator->run('C:\\inetpub\\wwwr...', Array)
#13 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#14 C:\inetpub\wwwroot\snipe-it-3.6.6\bootstrap\cache\compiled.php(1257): call_user_func_array(Array, Array)
#15 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#16 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 C:\inetpub\wwwroot\snipe-it-3.6.6\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '''' at line 1 (SQL: ALTER TABLE licenses CHANGE notes notes TEXT DEFAULT ''NULL'') in C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Connection.php:729
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Connection.php(685): Illuminate\Database\Connection->runQueryCallback('ALTER TABLE lic...', Array, Object(Closure))
#1 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Connection.php(458): Illuminate\Database\Connection->run('ALTER TABLE lic...', Array, Object(Closure))
#2 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Schema\Blueprint.php(83): Illuminate\Database\Connection->statement('ALTER TABLE lic...')
#3 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(229): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#4 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(130): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#5 C:\inetpub\wwwroot\snipe-it-3.6.6\bootstrap\cache\compiled.php(6327): Illuminate\Database\Schema\Builder->table('licenses', Object(Closure))
#6 C:\inetpub\wwwroot\snipe-it-3.6.6\database\migrations\2015_02_12_024100_change_license_notes_type.php(15): Illuminate\Support\Facades\Facade::__callStatic('table', Array)
#7 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(147): ChangeLicenseNotesType->up()
#8 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(117): Illuminate\Database\Migrations\Migrator->runUp('2015_02_12_0241...', 2, false)
#9 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(86): Illuminate\Database\Migrations\Migrator->runMigrationList(Array, Array)
#10 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(76): Illuminate\Database\Migrations\Migrator->run('C:\\inetpub\\wwwr...', Array)
#11 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#12 C:\inetpub\wwwroot\snipe-it-3.6.6\bootstrap\cache\compiled.php(1257): call_user_func_array(Array, Array)
#13 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#14 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\inetpub\wwwroot\snipe-it-3.6.6\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\inetpub\wwwroot\snipe-it-3.6.6\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main}

**Comment by TheWhexican87** [comment]
Same thing here as well:

[2017-07-31 10:11:31] production.ERROR: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '''' at line 1 in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php:457
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(457): PDO->prepare('ALTER TABLE lic...')
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'ALTER TABLE lic...', Array)
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(685): Illuminate\Database\Connection->runQueryCallback('ALTER TABLE lic...', Array, Object(Closure))
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(458): Illuminate\Database\Connection->run('ALTER TABLE lic...', Array, Object(Closure))
#4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Schema\Blueprint.php(83): Illuminate\Database\Connection->statement('ALTER TABLE lic...')
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(229): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#6 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(130): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#7 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(6327): Illuminate\Database\Schema\Builder->table('licenses', Object(Closure))
#8 C:\inetpub\wwwroot\snipe-it\database\migrations\2015_02_12_024100_change_license_notes_type.php(15): Illuminate\Support\Facades\Facade::__callStatic('table', Array)
#9 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(147): ChangeLicenseNotesType->up()
#10 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(117): Illuminate\Database\Migrations\Migrator->runUp('2015_02_12_0241...', 2, false)
#11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(86): Illuminate\Database\Migrations\Migrator->runMigrationList(Array, Array)
#12 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(76): Illuminate\Database\Migrations\Migrator->run('C:\\inetpub\\wwwr...', Array)
#13 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#14 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1257): call_user_func_array(Array, Array)
#15 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#16 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '''' at line 1 (SQL: ALTER TABLE licenses CHANGE notes notes TEXT DEFAULT ''NULL'') in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php:729
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(685): Illuminate\Database\Connection->runQueryCallback('ALTER TABLE lic...', Array, Object(Closure))
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(458): Illuminate\Database\Connection->run('ALTER TABLE lic...', Array, Object(Closure))
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Schema\Blueprint.php(83): Illuminate\Database\Connection->statement('ALTER TABLE lic...')
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(229): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(130): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#5 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(6327): Illuminate\Database\Schema\Builder->table('licenses', Object(Closure))
#6 C:\inetpub\wwwroot\snipe-it\database\migrations\2015_02_12_024100_change_license_notes_type.php(15): Illuminate\Support\Facades\Facade::__callStatic('table', Array)
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(147): ChangeLicenseNotesType->up()
#8 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(117): Illuminate\Database\Migrations\Migrator->runUp('2015_02_12_0241...', 2, false)
#9 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(86): Illuminate\Database\Migrations\Migrator->runMigrationList(Array, Array)
#10 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(76): Illuminate\Database\Migrations\Migrator->run('C:\\inetpub\\wwwr...', Array)
#11 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#12 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1257): call_user_func_array(Array, Array)
#13 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#14 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main}

**Comment by TheWhexican87** [comment]
Fixed my issue by downgrading to 10.0.14.  Something got changed in 10.2 that changes the syntax, so since the tables never got created, I removed 10.2 and installed 10.0.14, went through the steps, and it all got created without errors.

**Comment by snipe** [comment]
@TheWhexican87 weird - thanks for updating us!

**Comment by auviagroup** [comment]
snipe, I have the same problem, this is caused by an enforced schema standard in MariaDB starting from v10.2, affecting doctrine/dbal... see my comment in [https://github.com/doctrine/dbal/pull/2825](https://github.com/doctrine/dbal/pull/2825)
[This fix](https://github.com/doctrine/dbal/pull/2825/files) solved the problem for me.

> snipe-it-4-beta3, PHP 7.1.8, MariaDB 10.2.7, windows 10

I simply modified  the "C:\inetpub\wwwroot\snipe-it\vendor\doctrine\dbal\lib\Doctrine\DBAL\Schema\MySqlSchemaManager.php" as:
at line 159:
```
        $length = ((int) $length == 0) ? null : (int) $length;

        $options = array(
            'length'        => $length,
            'unsigned'      => (bool) (strpos($tableColumn['type'], 'unsigned') !== false),
            'fixed'         => (bool) $fixed,
            'default'       => isset($tableColumn['default']) ? $tableColumn['default'] : null,
            'notnull'       => (bool) ($tableColumn['null'] != 'YES'),
            'scale'         => null,
            'precision'     => null,
            'autoincrement' => (bool) (strpos($tableColumn['extra'], 'auto_increment') !== false),
            'comment'       => (isset($tableColumn['comment'])) ? $tableColumn['comment'] : null
        );
```
Replace with
```
        $length = ((int) $length == 0) ? null : (int) $length;

        $isNotNull = ($tableColumn['null'] !== 'YES');
        $columnDefault = (isset($tableColumn['default'])) ? $tableColumn['default'] : null;
        if ($columnDefault === 'NULL' && !$isNotNull) {
            // for mariadb 10.2+
            $columnDefault = null;
        }
        
        $options = array(
            'length'        => $length,
            'unsigned'      => (bool) (strpos($tableColumn['type'], 'unsigned') !== false),
            'fixed'         => (bool) $fixed,
            'default'       => $columnDefault,
            'notnull'       => $isNotNull,
            'scale'         => null,
            'precision'     => null,
            'autoincrement' => (bool) (strpos($tableColumn['extra'], 'auto_increment') !== false),
            'comment'       => (isset($tableColumn['comment'])) ? $tableColumn['comment'] : null
        );
```
I have no idea, what is the best approach to apply a fix on a dependency... hopefully you can fix it in snipe-it-4-beta4.

**Comment by mattcdavis1** [comment]
I'm experiencing this issue still with a clean install and Maria DB `Ver 15.1 Distrib 10.2.21-MariaDB`

For a temporary fix i just ran the migration locally on MySql and dumped into prod
