### ISSUE TITLE
Assets by Status chart in dashboard isn't showing deployed assets

### ISSUE THREAD

**Issue by tbradsha** [snipe/snipe-it#4290]
#### Expected Behavior (or desired behavior if a feature request)

All assets should show in the chart.

-----

#### Actual Behavior

Deployed assets aren't showing in the chart. This also occurs in the online demo.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

-Snipe-IT v4.0.13 build 323 (gc1f8db3)
-Upgrade
-PHP 5.6.28
-MySQL 5.7.15
-Windows Server 2012 R2 + Apache 2.4 (XAMPP)
-Manual installation

**Comment by snipe** [comment]
@tbradsha so that's not exactly a bug, but it's not really a feature either. Basically, since Deployed is a meta status, not an actual status, the results were confusing for some people when we included Deployed assets in that pie chart. Seems no matter which way we do it, people are going to want it to the other way. :-/

**Comment by tbradsha** [comment]
Regardless of "deployed" being a meta status, all assets should still show up in some status or another in the pie chart, right? Even if they are "ready to deploy" but checked out, I'd expect them to show as either "ready to deploy" or "deployed" (whichever people prefer), instead of being completely excluded from the chart. I don't know why "deployed" would be too confusing, though, as it's a mutually exclusive "status" (even though it's not a real status, it is either ready to deploy and unassigned, or ready to deploy and assigned).

**Comment by Blackyvk** [comment]
Is this the problem I have ? my pie chart is only showing Ready To Deploy assests that arent assigned to a user but, i have 25 laptops deployed that arent shown in the chart.

![image](https://user-images.githubusercontent.com/9063912/32291843-a63ff29c-bf14-11e7-94b5-02e4f0f129e4.png)

**Comment by snipe** [comment]
You're totally right. This should be fixed on master/develop now.

**Comment by CronKz** [comment]
Is this gonna be in the master branch any time soon? We are on 4.1.6 and this is still a thing

**Comment by snipe** [comment]
It's on master.

**Comment by CronKz** [comment]
So you've dicided to NOT show the status "deployed"... 
Well for me it would make more sense to see how many assets are "deployed" to someone or something and to only see "Ready to Deploy" for devices which are NOT deployed.
I don't know how this could confuse people, like you've mentioned above.
How about giving the User the choice what he wants to see in the Chart and what not?

**Comment by tbradsha** [comment]
Just to clarify: there is no such status as "deployed". They are all "ready to deploy", whether they are assigned or not. Perhaps a more relevant ticket/feature request is #4538? This issue was for an actual bug where some assets were not listed at all in the pie chart, and has been resolved.

**Comment by CronKz** [comment]
Well in my opinion "deployed" should be a status for itself. It doesn't make any sense for me to see devices wich are in fact deployed to a user or location but still shown in the chart as "ready to deploy". These devices are NOT "ready to deploy" in fact, because they aren't in my inventory anymore. Devices which are in fact in my Inventory AND are "ready to deploy" are the real devices which are "ready to deploy".

**Comment by snipe** [comment]
@CronKz Any deployable status that is checked out is deployed. We do this so that folks can have multiple status labels that may mean different things ("Temporarily loaned out", etc) but still be able to clearly see that they're deployed. Having multiple deployed statuses makes the interface more confusing for users.

**Comment by CronKz** [comment]
@snipe Ok, now I got ya. Makes sense... I know just made my own custom labels and now it shows the chart the way I want it :)
