### ISSUE TITLE
KeyCommands.php ErrorException after 4.2.0 to 4.3.0 upgrade

### ISSUE THREAD

**Issue by duel007** [snipe/snipe-it#5483]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgrading from 4.2.0 to 4.3.0, I get a "whoops" with the error file_put_contents(/var/www/html/storage/oauth-public.key): failed to open stream: No such file or directory

I verified the file exists within the container. I also tried running the php cleanup commands and php artisan migrate (Which finds nothing to migrate).

Reverting to my 4.2.0 container works normally.

**To Reproduce**
1. Start new container with database attached from previous 4.2.0 container
2. observe the error when visiting the main page of snipe-it

**Expected behavior**
Snipe-it starts with v4.3.0
**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.3.0
 - OS: Docker on Ubuntu
 - Web Server: Docker
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 66.0.3359.117

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

ErrorExceptionfile_put_contents(/var/www/html/storage/oauth-public.key): failed to open stream: No such file or directory
--
in KeysCommand.php (line 44)
at HandleExceptions->handleError(2, 'file_put_contents(/var/www/html/storage/oauth-public.key): failed to open stream: No such file or directory', '/var/www/html/vendor/laravel/passport/src/Console/KeysCommand.php', 44, array('rsa' => object(RSA), 'keys' => array('privatekey' =>

The full error has an RSA private key within it. I'm unsure if there is a security risk to posting that here, so i will leave it out for now.

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: Not able to attempt to reproduce this on demo
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on: Docker, Ubuntu
- What method you used to install Snipe-IT Docker
- Include what you've done so far in the installation, and if you got any error messages along the way.
Started in debug mode, ran cleanup commands, checked inside container for the file at that path
- Indicate whether or not you've manually edited any data directly in the database
No.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
(Or @HinchK)

**Comment by duel007** [comment]
As an update, I am still experiencing this issue however I noticed a couple things. Going to the homepage of snipe-it results in the whoops, but browsing to other pages (for example, /hardware or /licenses) does get a page to load, but with no visible assets.

**Comment by albelem** [comment]
Let me just add that "/var/www/html/storage/oauth-public.key" is a link pointing to a non-existant dir, same goes for "/var/www/html/storage/oauth-private.key". They both point to /var/lib/snipeit/keys which doesn't exist.

**Comment by duel007** [comment]
Resolved!

It turns out permissions were incorrect on my persistent directory. Snipe-IT could write within folders but not create them within /var/lib/snipeit. Propagating the correct permissions resolved the issue, 4.3.0 running as expected now.

**Comment by vegbrasil** [comment]
@duel007 I'm having the same issue, can you please detail how you managed to fix it?

**Comment by duel007** [comment]
@vegbrasil Your setup may differ. I am using docker, and passing through the /var/www directory to the host. I used chmod -r to propagate permissions, so that the user running the docker container also had full permissions to those files.

**Comment by vegbrasil** [comment]
@duel007 I'm also using Docker (`snipe/snipe-it:v4.2.0`) and mapping the `/var/lib/snipeit/` volume. There's no `keys` directory on my 4.2 install and creating it for 4.3+ does not solve the problem.

**Comment by albelem** [comment]
What I did was:

- run the 4.2 image;
- grab the keys (Search for them, they are on a different dir);
- run the latest image, and map the snipeit volume
- create the dir and copy the files

**Comment by vegbrasil** [comment]
@albelem It worked!

The files inside the 4.2 container are:

* `/var/www/html/storage/oauth-public.key`
* `/var/www/html/storage/oauth-private.key`

Running 4.4.1 fine now.

Thanks!

**Comment by albelem** [comment]
I'm glad it worked for you bud!
