### ISSUE TITLE
Unable to view Accessories menu option

### ISSUE THREAD

**Issue by pratikpul** [snipe/snipe-it#569]
Hi, I just have copied new code adding "accessories" menu option.
Unfortunately am unable to view that one. Please help!!

**Comment by snipe** [comment]
What does "unable to view" mean?

**Comment by pratikpul** [comment]
Unable to view means "Accessories" is missing
![capture](https://cloud.githubusercontent.com/assets/11059882/6388601/b40e9c5e-bdc1-11e4-8b82-ba1d04e030e3.JPG)

**Comment by snipe** [comment]
What version did you download? A little more info here would be helpful.

**Comment by pratikpul** [comment]
The latest one ... 1.2.5
downloaded from "https://github.com/snipe/snipe-it"

**Comment by snipe** [comment]
What branch tho?

**Comment by snipe** [comment]
Accessories aren't in a release yet, only on the `develop` branch, and the functionality isn't complete. It should be out in the 1.2.6 release.

**Comment by pratikpul** [comment]
develop :)

**Comment by snipe** [comment]
No idea then. It's in the develop branch, and you can see it on the demo. My only guess is that you didn't copy all of the files over.

**Comment by pratikpul** [comment]
Yes, I copied all the files over as well... also the same problem I am facing MAC Address field is not showing up when adding assets. I believe it has been fixed now!

**Comment by snipe** [comment]
"also the same problem I am facing MAC Address field is not showing up when adding assets. I believe it has been fixed now!" <-- I don't actually understand what this means.

**Comment by pratikpul** [comment]
I mean in v1.2.5 you have Fixed bug where MAC address was not showing on models with it enabled.
> For me it is still not showing on models with it enabled.

**Comment by snipe** [comment]
I still don't understand. Is the MAC address showing for you or not?

**Comment by pratikpul** [comment]
not showing dear.

**Comment by snipe** [comment]
I can't reproduce either of these, and they are both working on the demo. For the MAC address, did you enable it in the asset model? MAC addresses are turned on at the asset model level, since some types of assets won't have a MAC address.

Please don't call me "dear". I find it very condescending.

**Comment by snipe** [comment]
You're definitely not running the latest `develop` branch. The icon in your screenshot for "reports" was changed tonight, and that change is on develop.

**Comment by pratikpul** [comment]
Okay.. Sorry for that will take care of it.
It could be I missed something while trying to update... I replaced all new downloaded files (snipe-it-develop.zip) with existing application but it (MAC Address, Accessories) not shown up.
Can you help me if I have missed update process?

**Comment by snipe** [comment]
I typically recommend updating via `git clone` versus downloading the zip, as it will be easier to fetch updated files moving forward. 

If you'd still like to go the zip route, try downloading from here: https://github.com/snipe/snipe-it/archive/develop.zip

**Comment by pratikpul** [comment]
Got it will try git clone now!
I must say Biggggggg "Thank Youuuuuu" for developing a wonderful application Snipe. Fullfilling most of all the requirements.

**Comment by snipe** [comment]
Let me know how you make out. 

As I mentioned, Accessories isn't quite done yet. Should be in another day or so.

**Comment by pratikpul** [comment]
It worked!
Can see accessories and graph as well. (Still MAC address "not" showing up)
Thanks for the wonderful support. :)

**Comment by snipe** [comment]
Remember that you have to edit the Asset Model to check the "use MAC address" checkbox, and then go back and edit the asset itself.

**Comment by pratikpul** [comment]
Yeah! doing by the same way.
I believe it should be shown when creating asset.

**Comment by snipe** [comment]
Yeah, we'll be making that flow a little easier over the next week or two.
