### ISSUE TITLE
Asset location cannot be changed without performing a check-in or check-out

### ISSUE THREAD

**Issue by JonathonReinhart** [snipe/snipe-it#6743]
You cannot change the location of an asset except by checking-in or checking-out an asset.

Use cases:
- An item remains checked-in to IT, but is being moved from one storage area to another.
  - Today (v4.6.7) one must check-out the item to an arbitrary user/location, then set the item's location on check-in
  - It would be better to simply change the item's location without performing a check-out/check-in
- An item remains checked-out to a user, but is being moved from one work area to another.
  - Today (v4.6.7) one must check-in the item, then check-out the item to a location
  - It would be better to simply leave the item checked-out to that user, but change the item's location

**Comment by ZephyriusOne** [comment]
You can change the assets location another way, but it's finicky at best as you can only update the default location or BOTH, not just the actual location.

When on the Assets page, select the checkbox of the asset(s) you want to change location, and go to "Edit" in the drop down menu. From there, you can update both default and actual location.

![image](https://user-images.githubusercontent.com/45017543/53104223-f8acfc00-34fc-11e9-84d6-6ba18a53dd19.png)

![image](https://user-images.githubusercontent.com/45017543/53104292-1aa67e80-34fd-11e9-8621-4c9ffb6edfba.png)

**Comment by shinjijai** [comment]
When we first started using SnipeIT we just imported all the asset in with the default location to where the were located. The fact that our users didn't have locations associated with them at that time caused all our assets to not have a location field. 

I recently noticed this and tried to fix it by checking in and checking out all the assets back to the user (running v4.6.4) using the API and found out that doing so removed all the names associated to our assets. We didn't noticed this issue until it was too late. So word of warning, if you do use the API to do this, make sure you check to make sure the asset names aren't affected by this.

**Comment by snipe** [comment]
@shinjijai That was fixed a few versions ago. If you don't want to update a field, don't pass it via the API.

**Comment by shinjijai** [comment]
I'll update to the latest version soon, but when I did checkin, I didn't pass any values, and with checkout I just pass the user's ID for which the asset was checkout to. Either way, I will upgrade to the latest version. Thanks!

**Comment by JonathonReinhart** [comment]
Dammit stale bot. Yes this is still relevant. It hasn't been fixed AFAIK.

**Comment by timwsuqld** [comment]
@snipe Can you please reopen this. Also, the stale bot doesn't seem to be seeing comments for reopening it.

**Comment by ohmer1** [comment]
@snipe please, could you reopen this ticket, the issue is still relevant with the latest release. I can set a location when I check out an asset, but there is no way to : 

- Edit the asset location without check in and out again  (use case: asset is moved to stockage location A to stockage location B)
- Set an asset location when creating a new asset (use case: I just received a new asset I need to configure before I can attribute it to a user).

Sure, I can check in the asset to the stockage room, but this mark the asset as deployed while it's not, it's brand new in the box!

**Comment by BernardMcWeeney** [comment]
I've found a work around

Select the asset item in the list uisng the checkbox, then click edit as if you were doing a bulk edit
![image](https://github.com/snipe/snipe-it/assets/99593468/258ed84e-ed70-4a2e-8e1d-ae824431d22c)

And then the feilds for changing the default and acutal location appear:

![image](https://github.com/snipe/snipe-it/assets/99593468/72344c38-725f-4808-8122-9b0ab42464dc)

**Comment by soxhi8** [comment]
> work around

Emphasis on the workaround. It would be really helpful to have the actual location on the standard edit page for each asset.

**Comment by bilias** [comment]
Can this be re-opened? 

Only way to change actual location is to check-in/check-out item (after updating default location first) or perform the bulk edit workaround.

Thanks
