### ISSUE TITLE
On 4.7.6 performing a basic lookup for anything results in no displayed results - searching for exact item finds the specified details

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#7349]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode - I have not 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When upgrading to 4.7.6 and loading the main page for assets, accessories, licenses, users or any other blanket item no results are displayed. 

Searching for a specific dataset will show the detail of that dataset

May be related to the Status Labels and if they were modified, I'm seeing mixed results on the DEMO, in my production environment I'm unable to find any results for any dataset. Still investigating.

**To Reproduce**
1. Go to 'Assets'
2. Click on 'Ready to Deploy / All Deployed'
3. Find no results 
4. Go to 'People' 
5. Click on 'Alejandro Frey'
6. Click on 'Assets'
7. Click on '73243'
8. See asset details

**Expected behavior**
Datasets results to be displayed immediately without needing to know the exact detail of a specific dataset.

**Screenshots**
![chrome_n7CvvkcZMn](https://user-images.githubusercontent.com/14837699/62942682-d0fd6900-bda6-11e9-8a20-0c4dd0bcee59.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.7.6
 - OS: CentOS7
 - Web Server: Apache
 - PHP Version 7.1.30

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 75.0.3770.142

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
Upgrade
- What OS and web server you're running Snipe-IT on: 
CentOS 7 with Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) 
Install script
- Include what you've done so far in the installation, and if you got any error messages along the way. 
While upgrading I see an error *cannot delete /var/www/html/snipeit/vendor/squizlabs/php_codesniffer where everything in here is owned by root and I cannot delete .gitattributes.*
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Jarli01** [comment]
From within the Clicking on 'Assets >List All' also shows 0 results. Performing a search in either field does end up displaying the asset details.

**Comment by Jarli01** [comment]
The error as displayed within the DEMO environment from chrome

	VM135:1 GET https://demo.snipeitapp.com/api/v1/hardware?status=Deployed&order_number=&company_id=&status_id=&sort=name&order=asc&offset=0&limit=100 500
	(anonymous)	@	VM135:1
	send	@	all.js?id=bf1b244…:3
	ajax	@	all.js?id=bf1b244…:3
	o.initServer	@	bootstrap-table.min.js:8
	BootstrapTable.initServer	@	bootstrap-table-cookie.js?v=1:289
	o.init	@	bootstrap-table.min.js:7
	BootstrapTable.init	@	bootstrap-table-mobile.js:91
	BootstrapTable.init	@	bootstrap-table-cookie.js?v=1:279
	o	@	bootstrap-table.min.js:7
	(anonymous)	@	bootstrap-table.min.js:8
	each	@	all.js?id=bf1b244…:1
	each	@	all.js?id=bf1b244…:1
	a.fn.bootstrapTable	@	bootstrap-table.min.js:8
	(anonymous)	@	hardware?status=Deployed:1173
	u	@	all.js?id=bf1b244…:2
	c	@	all.js?id=bf1b244…:2
	setTimeout (async)		
	(anonymous)	@	all.js?id=bf1b244…:2
	u	@	all.js?id=bf1b244…:2
	fireWith	@	all.js?id=bf1b244…:2
	fire	@	all.js?id=bf1b244…:2
	u	@	all.js?id=bf1b244…:2
	fireWith	@	all.js?id=bf1b244…:2
	ready	@	all.js?id=bf1b244…:2
	f	@	all.js?id=bf1b244…:1

**Comment by Jarli01** [comment]
The error from the console from **All Assets**

    Failed to load resource: the server responded with a status of 500 () api/v1/hardware?stat...ffset=0&limit=100:1

**Comment by wirestyle22** [comment]
I'm also seeing the same error

**Comment by gfreeman1** [comment]
I am also experiencing the same on 4.7.6. Clicking the Refresh button next to the search box, without entering a search term or doing anything else, displays results as expected.

Also, running the following on the server seems to have fixed the issue for me, as I am now seeing results as expected without having to click the Refresh button. I tested this after clearing my browser's cookies as well as in an incognito window.

`sudo -u snipeitapp /usr/bin/php /var/www/snipeit/artisan cache:clear`

**Comment by Jarli01** [comment]
@gfreeman1 I have no change here after attempting that.

**Comment by snipe** [comment]
I'd need debug logs in order to tell you what's happening here.

Check that the dates in your assets table make sense, and that you don't have any bonkers warranty ranges (13000 months, etc)

**Comment by Jarli01** [comment]
Here is the end of the laravel.log with debug mode turned on. 

	[2019-08-15 08:26:59] production.ERROR: ReflectionException: Class Barryvdh\Cors\HandleCors does not exist in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:752
	Stack trace:
	#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('Barryvdh\\Cors\\H...')
	#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Barryvdh\\Cors\\H...')
	#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('Barryvdh\\Cors\\H...', Array)
	#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make('Barryvdh\\Cors\\H...', Array)
	#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(215): Illuminate\Foundation\Application->make('Barryvdh\\Cors\\H...')
	#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Illuminate\Http\JsonResponse))
	#6 /var/www/html/snipeit/public/index.php(63): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\JsonResponse))
	#7 {main}
	[2019-08-15 08:26:59] production.ERROR: Class Barryvdh\Cors\HandleCors does not exist {"userId":1,"email":"dustin.beuerlein@partnersandnapier.com","exception":"[object] (ReflectionException(code: -1): Class Barryvdh\\Cors\\HandleCors does not exist at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:752)
	[stacktrace]
	#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('Barryvdh\\\\Cors\\\\H...')
	#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build('Barryvdh\\\\Cors\\\\H...')
	#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve('Barryvdh\\\\Cors\\\\H...', Array)
	#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\\Container\\Container->make('Barryvdh\\\\Cors\\\\H...', Array)
	#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(215): Illuminate\\Foundation\\Application->make('Barryvdh\\\\Cors\\\\H...')
	#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
	#6 /var/www/html/snipeit/public/index.php(63): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
	#7 {main}
	"}

**Comment by Jarli01** [comment]
The same exact error is present with the most current software. 

![chrome_gbDUrVdUWp](https://user-images.githubusercontent.com/14837699/63096759-c07ef700-bf3c-11e9-9448-da8dad482cf7.png)

**Comment by snipe** [comment]
@Jarli01 what's your output when you run `composer install --no-dev`?

**Comment by Jarli01** [comment]
Will check in one moment

**Comment by Jarli01** [comment]
From my working directory of `/var/www/html/snipeit`

running `composer install --no-dev` I get `composer install --no-dev -bash: composer: command not found`

**Comment by snipe** [comment]
However it is you usually run composer then. `php composer.phar install --no-dev`

**Comment by Jarli01** [comment]
php composer.phar install --no-dev
	Loading composer repositories with package information
	Installing dependencies from lock file
	Package operations: 3 installs, 41 updates, 29 removals
	  - Removing squizlabs/php_codesniffer (3.4.2)


	  [RuntimeException]
	  Could not delete /var/www/html/snipeit/vendor/squizlabs/php_codesniffer/.gi
	  tattributes:


	install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-c                                                                                                                                                             ustom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest                                                                                                                                                             ] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative]                                                                                                                                                              [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by Jarli01** [comment]
Which I saw that message initially, and reported it in the OP.

**Comment by Jarli01** [comment]
Those files have these permissions. 

	php_codesniffer]$ ls -la
	total 68
	drwxr-xr-x.  6 root root  4096 May 29 15:50 .
	drwxr-xr-x.  3 root root    29 May 29 15:50 ..
	-rw-r--r--.  1 root root 10084 Apr 10 19:49 autoload.php
	drwxr-xr-x.  2 root root    68 Apr 10 19:49 bin
	-rw-r--r--.  1 root root   187 Apr 10 19:49 CodeSniffer.conf.dist
	-rw-r--r--.  1 root root  1083 Apr 10 19:49 composer.json
	-rw-r--r--.  1 root root   638 Apr 10 19:49 CONTRIBUTING.md
	-rw-r--r--.  1 root root   157 Apr 10 19:49 .gitattributes
	-rw-r--r--.  1 root root    73 Apr 10 19:49 .gitignore
	-rw-r--r--.  1 root root  1533 Apr 10 19:49 licence.txt
	-rw-r--r--.  1 root root  6123 Apr 10 19:49 phpcs.xml.dist
	-rw-r--r--.  1 root root  5785 Apr 10 19:49 phpcs.xsd
	-rw-r--r--.  1 root root   340 Apr 10 19:49 phpstan.neon
	-rw-r--r--.  1 root root  5513 Apr 10 19:49 README.md
	drwxr-xr-x.  3 root root    81 Apr 10 19:49 scripts
	drwxr-xr-x. 11 root root   238 Apr 10 19:49 src
	drwxr-xr-x.  4 root root   119 Apr 10 19:49 tests

**Comment by snipe** [comment]
I'm going to guess maybe your permissions on your vendor dir (or subdirs) is off? (Vendor files shouldn't be run as root, and composer shouldn't be run as root, as we say elsewhere in the documentation.)

**Comment by Jarli01** [comment]
Yeah, the vendor folder is owned by root, as well as upgrade.php.bck. 

But how/when would this have been overwritten? (asking myself).

**Comment by Jarli01** [comment]
So reset the permissions on `vendor` to be apache:apache?

**Comment by snipe** [comment]
If you accidentally sudo'd while you were running composer at some point, the new vendor files would be owned by root, since root put them there.

> So reset the permissions on vendor to be apache:apache?

Yeah, or whatever other user you'd normally use

**Comment by Jarli01** [comment]
I've been particular careful because I had these issues in the past. I was on vacation for 2 weeks. Maybe a co-worker broke something. 

Can you confirm that the demo is working as well, as I saw similar issues in there.

**Comment by snipe** [comment]
No issues on the demo

**Comment by snipe** [comment]
(Issues sometimes show up on the demo because of weird data from people picking around with the API. I did see a 500 error there recently but it was resolved by re-seeding the database back to normal.)

**Comment by Jarli01** [comment]
Even with the vendors folder owned by apache:apache (which is what the install script sets up IIRC) and rebooting I still have no visible results. 

Running `php composer.phar install --no-dev` I still can't delete that .gitattributes file

**Comment by Jarli01** [comment]
Permissions didn't right recursively. .

**Comment by snipe** [comment]
You have to use the -R attribute on dirs if you want changes to apply recursively. 

`chown -R apache.apache vendor`

**Comment by Jarli01** [comment]
Yeah I just did to fix that, was a typo on my part.

**Comment by Jarli01** [comment]
I still am getting ` Could not delete /var/www/html/snipeit/vendor/squizlabs/php_codesniffer/.gitattributes:`

**Comment by snipe** [comment]
Then just delete the vendor directory and re-run composer install.

**Comment by Jarli01** [comment]
So when I run it, without elevation I get `php composer.phar install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 106 installs, 0 updates, 0 removals  [RuntimeException]
  /var/www/html/snipeit/vendor does not exist and could not be created.`

If I run it as my elevation user, the folder exist but is owned by root. . .

**Comment by Jarli01** [comment]
But the search and display functionality is now working. . . so eh? weird.

**Comment by snipe** [comment]
Then you'll need to fix permissions one level up.

**Comment by Jarli01** [comment]
So `chown -R snipeit apache:apache` from /var/www/html, correct?

**Comment by snipe** [comment]
Typically yes, but it sort of depends how you normally run things

**Comment by Jarli01** [comment]
Usually i just log into the server as my user account, and update without sudo. 

It's weird as the system is now operating *correctly* from what I can tell with 4.7.6 even though vendor is owned by root again. . .

**Comment by snipe** [comment]
I'm going to close this one for now, since everything seems to be working okay.

**Comment by Jarli01** [comment]
No worries, might be time I just rebuild this install or get my company to have you host it. . . grumble grumble..
